site_name: SSE Documentantion Example
repo_url: https://github.com/RPAlessio/sse-mkdocs-exercise
nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Installation': 'compilation-and-installation.md'
        - 'Getting Started': 'how-to.md'

